version: "2.3"

services:
  links:
    build:
      context: .
    container_name: links
    environment:
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: links
    env_file:
      - environ
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine3.13

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: links
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

