[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
  | venv
  | Makefile
  | README.md
  | setup.cfg
)/
'''

[tool.isort]
line_length=88
known_django = ["django"]
sections=["FUTURE","STDLIB","DJANGO","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
include_trailing_comma = true
multi_line_output = 3
skip = ["migrations","node_modules","venv","static"]
lines_after_imports = 2
force_grid_wrap=0
use_parentheses=true